### ISSUE TITLE
Upload of the .jar file

### ISSUE THREAD

**Issue by chunkleader** [Zennoe/Bierbrauerei-java#14]
Thomas, could you please upload the jar file of our project so that it can easily been opened?

**Comment by Zenneo** [comment]
soon TM


Mit freundlichen Grüßen

Thomas Schmitz

2016-07-29 15:28 GMT+02:00 chunkleader <notifications@github.com>:

**Comment by Zennoe** [comment]
@chunkleader @EragonBromsohn @LukasEitel @PierreGames 
Bierbrauerei-java wurde so eben als JAR veröffentlich und sollte auf allen Plattformen laufen:
https://github.com/Zennoe/Bierbrauerei-java/releases/tag/v1.1

Mit GTK hatte die UI jedoch kleine Probleme, die in Windows nicht auftreten. Deshalb weiß ich nicht, wie die UI in macOS aussehen wird.
